"""
Signal infrastructure for trading strategies.

This module provides the core signal classes and interfaces that enable
separation of signal generation from signal execution.
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, Union
from datetime import datetime
import uuid


class SignalType(Enum):
    """Enumeration of different signal types."""   
    # Trend State Signals
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    TREND_NEUTRAL = "TREND_NEUTRAL"
    TREND_CHANGE = "TREND_CHANGE"
    
    # Momentum Signals
    MOMENTUM_ACCELERATING = "MOMENTUM_ACCELERATING"
    MOMENTUM_DECELERATING = "MOMENTUM_DECELERATING"
    MOMENTUM_REVERSAL = "MOMENTUM_REVERSAL"
    
    # Volatility Signals
    VOLATILITY_HIGH = "VOLATILITY_HIGH"
    VOLATILITY_LOW = "VOLATILITY_LOW"
    VOLATITY_BREAKOUT = "VOLATITY_BREAKOUT"
    
    # Risk Management Signals
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    POSITION_SIZE_ADJUST = "POSITION_SIZE_ADJUST"
    
    # Market Condition Signals
    MARKET_TRENDING = "MARKET_TRENDING"
    MARKET_RANGING = "MARKET_RANGING"
    MARKET_VOLATILE = "MARKET_VOLATILE"
    MARKET_QUIET = "MARKET_QUIET"
    
    # Confirmation Signals
    SIGNAL_CONFIRMED = "SIGNAL_CONFIRMED"
    SIGNAL_FAILED = "SIGNAL_FAILED"
    SIGNAL_PENDING = "SIGNAL_PENDING"


class SignalPriority(Enum):
    """Signal priority levels for handling multiple signals."""
    CRITICAL = 1    # Must be handled immediately (e.g., stop loss)
    HIGH = 2       # Important signals (e.g., primary trading signals)
    MEDIUM = 3     # Regular signals (e.g., trend changes)
    LOW = 4        # Informational signals (e.g., market conditions)


@dataclass
class Signal:
    """
    Represents a trading signal generated by a strategy.
    
    Attributes:
        signal_type: The type of signal being generated
        timestamp: When the signal was generated (ISO format string)
        price: The price at which the signal was generated
        token: The instrument token symbol
        confidence: Signal confidence level (0.0 to 1.0)
        priority: Signal priority for handling order
        metadata: Strategy-specific data and context
        signal_id: Unique identifier for the signal
        source: Which strategy/component generated the signal
        expires_at: Optional expiration time for time-sensitive signals
    """
    signal_type: SignalType
    timestamp: str
    price: float
    token: str
    confidence: float = 1.0
    priority: SignalPriority = SignalPriority.MEDIUM
    metadata: Dict[str, Any] = field(default_factory=dict)
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source: str = ""
    expires_at: Optional[str] = None
    
    def __post_init__(self):
        """Validate signal data after creation."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0")
        
        if self.price <= 0:
            raise ValueError("Price must be positive")
        
        if not self.timestamp:
            self.timestamp = datetime.now().isoformat()
    
    def is_expired(self) -> bool:
        """Check if the signal has expired."""
        if not self.expires_at:
            return False
        return datetime.now() > datetime.fromisoformat(self.expires_at)
    
    def is_valid(self) -> bool:
        """Check if the signal is still valid."""
        return not self.is_expired() and self.confidence > 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for serialization."""
        return {
            'signal_id': self.signal_id,
            'signal_type': self.signal_type.value,
            'timestamp': self.timestamp,
            'price': self.price,
            'token': self.token,
            'confidence': self.confidence,
            'priority': self.priority.value,
            'metadata': self.metadata,
            'source': self.source,
            'expires_at': self.expires_at,
            'is_valid': self.is_valid(),
            'is_expired': self.is_expired()
        }


class SignalHandler:
    """
    Base class for signal handlers.
    
    Signal handlers are responsible for processing signals
    and taking appropriate actions (e.g., executing trades).
    """
    
    def __init__(self, name: str = ""):
        self.name = name or self.__class__.__name__
        self.processed_signals: List[Signal] = []
    
    def handle_signal(self, signal: Signal) -> Optional[Any]:
        """
        Handle a single signal.
        
        Args:
            signal: The signal to handle
            
        Returns:
            Result of handling the signal (e.g., Trade object)
        """
        raise NotImplementedError("handle_signal must be implemented by subclasses")
    
    def handle_signal_batch(self, batch: SignalBatch) -> List[Any]:
        """
        Handle a batch of signals.
        
        Args:
            batch: Batch of signals to handle
            
        Returns:
            List of results from handling signals
        """
        results = []
        for signal in batch.get_valid_signals():
            result = self.handle_signal(signal)
            if result is not None:
                results.append(result)
                self.processed_signals.append(signal)
        
        return results
    
    def can_handle_signal(self, signal: Signal) -> bool:
        """
        Check if this handler can process the given signal.
        
        Args:
            signal: The signal to check
            
        Returns:
            True if the handler can process the signal
        """
        return True  # Base implementation handles all signals
    
    def get_processed_signals(self) -> List[Signal]:
        """Get the history of processed signals."""
        return self.processed_signals.copy()


class SignalFilter:
    """
    Base class for signal filters.
    
    Signal filters can be used to validate, modify, or block signals
    before they reach handlers.
    """
    
    def __init__(self, name: str = ""):
        self.name = name or self.__class__.__name__
    
    def filter_signal(self, signal: Signal) -> Optional[Signal]:
        """
        Filter a single signal.
        
        Args:
            signal: The signal to filter
            
        Returns:
            Modified signal, None to block the signal, or original signal
        """
        return signal
    
    def filter_batch(self, batch: SignalBatch) -> SignalBatch:
        """
        Filter a batch of signals.
        
        Args:
            batch: The signal batch to filter
            
        Returns:
            Filtered signal batch
        """
        filtered_signals = []
        for signal in batch.signals:
            filtered_signal = self.filter_signal(signal)
            if filtered_signal is not None:
                filtered_signals.append(filtered_signal)
        
        return SignalBatch(
            signals=filtered_signals,
            batch_timestamp=batch.batch_timestamp,
            batch_id=batch.batch_id,
            metadata=batch.metadata
        )


class SignalComposer:
    """
    Utility class for combining and composing multiple signals.
    """
    
    @staticmethod
    def combine_signals(signals: List[Signal], 
                      operation: str = "AND") -> Optional[Signal]:
        """
        Combine multiple signals into a single signal.
        
        Args:
            signals: List of signals to combine
            operation: How to combine ("AND", "OR", "WEIGHTED_AVERAGE")
            
        Returns:
            Combined signal or None
        """
        if not signals:
            return None
        
        if operation == "AND":
            # All signals must be valid
            valid_signals = [s for s in signals if s.is_valid()]
            if len(valid_signals) != len(signals):
                return None
            
            # Use the lowest confidence
            combined_confidence = min(s.confidence for s in signals)
            
        elif operation == "OR":
            # Any valid signal is sufficient
            valid_signals = [s for s in signals if s.is_valid()]
            if not valid_signals:
                return None
            
            # Use the highest confidence
            combined_confidence = max(s.confidence for s in signals)
            
        elif operation == "WEIGHTED_AVERAGE":
            # Weighted average of confidences
            valid_signals = [s for s in signals if s.is_valid()]
            if not valid_signals:
                return None
            
            total_confidence = sum(s.confidence for s in valid_signals)
            combined_confidence = total_confidence / len(valid_signals)
            
        else:
            raise ValueError(f"Unknown operation: {operation}")
        
        # Create combined signal
        combined_signal = Signal(
            signal_type=signals[0].signal_type,  # Use first signal's type
            timestamp=signals[0].timestamp,
            price=signals[0].price,
            token=signals[0].token,
            confidence=combined_confidence,
            priority=min(s.priority for s in signals),  # Use highest priority
            metadata={
                "composed_from": [s.signal_id for s in signals],
                "operation": operation,
                "original_signals": [s.to_dict() for s in signals]
            },
            source="SignalComposer"
        )
        
        return combined_signal
    
    @staticmethod
    def create_confirmation_signal(original_signal: Signal, 
                                confirmed: bool = True) -> Signal:
        """
        Create a confirmation or failure signal for an original signal.
        
        Args:
            original_signal: The signal to confirm/fail
            confirmed: Whether the signal is confirmed
            
        Returns:
            Confirmation or failure signal
        """
        signal_type = SignalType.SIGNAL_CONFIRMED if confirmed else SignalType.SIGNAL_FAILED
        
        return Signal(
            signal_type=signal_type,
            timestamp=datetime.now().isoformat(),
            price=original_signal.price,
            token=original_signal.token,
            confidence=0.9 if confirmed else 0.1,
            priority=SignalPriority.MEDIUM,
            metadata={
                "original_signal_id": original_signal.signal_id,
                "original_signal_type": original_signal.signal_type.value,
                "confirmation_timestamp": datetime.now().isoformat()
            },
            source="SignalComposer"
        )